language: php

php:
  - 7.1

env:
  global:
    - SEND_COVERAGE=false
    - PHPSTAN=false

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
      env: SEND_COVERAGE=true
    # phpstan
    - php: 7.1
      env: PHPSTAN=true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer validate

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - if [[ "$PHPSTAN" = false && "$SEND_COVERAGE" = true ]]; then ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run; fi
  - if [[ "$PHPSTAN" = false && "$SEND_COVERAGE" = true ]]; then ./vendor/bin/phpunit -c phpunit.xml.dist --verbose --coverage-clover=coverage.xml; fi
  - if [[ "$PHPSTAN" = true && "$SEND_COVERAGE" = false ]]; then ./vendor/bin/phpstan analyse -c phpstan.neon -l 6 src/TestingHelper; fi

after_success:
  - if [[ "$PHPSTAN" = false && "$SEND_COVERAGE" = true ]]; then bash <(curl -s https://codecov.io/bash); fi